project_id = "kogxlpjzzmedlfdzwwvi"

[functions.generate-podcast-script]
verify_jwt = false

[functions.generate-podcast-audio]
verify_jwt = false

[functions.list-voices]
verify_jwt = false

[functions.optimize-podcast-script]
verify_jwt = false

[functions.generate-podcast-video]
verify_jwt = false

[functions.generate-ad-video]
verify_jwt = false

[functions.add-captions-music]
verify_jwt = false

[functions.enhance-video-prompt]
verify_jwt = false

[functions.save-to-drive]
verify_jwt = false

[functions.joggai-create-video]
verify_jwt = false

[functions.joggai-proxy]
verify_jwt = false
